// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type Book struct {
	ID        int64
	Title     string
	Author    string
	Volume    sql.NullString
	Edition   sql.NullString
	Publisher sql.NullString
	Year      string
}

type Chapter struct {
	ID     int64
	BookID int64
	Number int64
	Name   string
}

type Exercise struct {
	ID        int64
	Number    int64
	ChapterID int64
}

type Image struct {
	ExID     int64
	FileName string
	Sequence int64
}
